### ISSUE TITLE
Item.save_tags : bug lorsque deux tags avec des casses différentes sont dans la liste

### ISSUE THREAD

**Issue by svergeylen** [svergeylen/collector#112]
Les tags doivent etre unique (case insensitve), mais lorsqu'on sauve les tags dans l'item, on tente de créer les tags qui n'existent pas encore... or, ce processus de création ne tient pas compte de la casse et ne fonctionne pas à partir du moment ou il y a dans la liste de tags à sauver deux tags qui sont identiques à part leur casse : ex : van hamme et Van Hamme....

**Comment by dvergeylen** [comment]
Je ferais

```ruby
# app/models/tag.rb
before_save: :ensure_lowercase # sauve toujours en lowercase

def ensure_lowercase
  self.name.lowercase
end

# Affiche toujours avec majuscules (van hamme → Van Hamme)
def nice_name
  self.name.titleize
end
```
