### ISSUE TITLE
focus sur le champ recherche

### ISSUE THREAD

**Issue by vergeylen** [svergeylen/collector#19]
Ajouter le champ de recherche sur la page categories#show, de façon a faire une recherche uniquement dans cette catégorie.
Il faut mettre le focus sur ce chap recherche au chargement de la page.

**Comment by svergeylen** [comment]
C'est fait.

- Les résultats s'affichent dès que 2 lettres sont tapées.
- Il y a une option dans chauqe catégorie qui permet de choisir si on veut afficher cette barre de recherche ou pas (pas de sens pour les bonsais par exemple)
- Le premier résultat de recherche est sélectionnable en faisant "TAB" puis "ENTER"... 

Il reste un bug quand on fait "enter" dans champ de recherche. Il suffit de ne pas faire enter du tout pour le moment

**Comment by vergeylen** [comment]
Très performant :

il n'y a pas de bug chez moi : je tape 2 lettres, puis directement 
sélection avec Tab, puis Enter et.... hop

PS: voir 2 issues ajoutées dans le programme de travail ;-)

Bisous (avec fierté)
L.

**Comment by svergeylen** [comment]
Super. Je cloture cette demande-ci alors.
