### ISSUE TITLE
Support Emoji

### ISSUE THREAD

**Issue by svergeylen** [svergeylen/collector#2]
Passer la database en utf8mb4 et vérifier que le stockage des caractères en 4 bytes est OK.
Ajouter un interface graphique pour choisir son emoji

https://www.sois-net.fr/rails-bien-preparer-sa-bdd-pour-stocker-des-emoji/

* [x] Support des Emojis dans la DB
* [ ] Affichage d'un menu WYSIWYG pour les sélectionner quand on tape un message

**Comment by svergeylen** [comment]
https://blog.metova.com/add-emoji-support-rails-4-mysql-5-5/

**Comment by svergeylen** [comment]
@dvergeylen A priori, j'ai fait la migration de la database en production.... Tu peux réesayer le support des emoji (je n'ai pas trouvé comment écrire un code unicode dans le textarea donc éventuellement, dis moi comment faire)

**Comment by dvergeylen** [comment]
Ça a l'air de passer :+1:  :

![capture du 2017-10-16 09-47-22](https://user-images.githubusercontent.com/8804879/31600532-28af7678-b257-11e7-8d6e-3c30dfd2127d.png)

Pour en faire sous Linux, Ctrl + Shift + u puis tu tapes la réf unicode (ex: 1F605 → 😅)

Si ça enregistre correctement en DB, pour moi on peut fermer ce thread ;-)

**Comment by svergeylen** [comment]
J'ai tenté ce widget, mais ca lagge fortement et je trouve que le résultat est un peu pourri...

https://github.com/wedgies/jquery-emoji-picker

Le soucis majeur, c'est que les icones sont codées en HEX dans le css même.... d'ou un temps de chargement assez long.

L'autre souci, c'est qu'un fois l'emoji sélectionné dans la galerie, il reste en noir/blanc dans le post, car Ubuntu n'est pas capable de faire le rendu d'une police avec couleur (ou alors c'est vraiment très bricolage et nécessite j'aout de paquet coté client).

Piste : intégrer une police de caractères dans le site web (téléchargée une seule fois puis dans le cache) qui pourrait faire le rendu des emoji en couleurs, puis faire un picker de caractère dans cette police de caractère...

**Comment by svergeylen** [comment]
ca marche, et les emoji picker seront natifs dans les browser prochainement... je ferme

**Comment by dvergeylen** [comment]
Ah bon?? 😎

Tu as un lien ? 😇

**Comment by svergeylen** [comment]
moi, j'utilise ceci, mais pas envore dans firefox (trop dommage)
et puis c'est bizarre, mais dans firefox, le rendu des emojis est différents que dans gedit...

https://askubuntu.com/questions/1045915/how-to-insert-an-emoji-into-a-text-in-ubuntu-18-04
