### ISSUE TITLE
Catégorie Bd - Nouvel ajout

### ISSUE THREAD

**Issue by vergeylen** [svergeylen/collector#21]
Suggestion : à l'affichage de l'écran d'un série Bd, 
soit directement faire clignoter le curseur dans le champ "Ajout" ;
soit directement faire clignoter le curseur dans le champ "Recherche"
qui sont les 2 actions généralement effectuées sur les écrans "séries"

**Comment by svergeylen** [comment]
Le problème avec cela serait double : 
 - la page va scroller en bas de page lorsque le focus est mis sur l'ajout
 - le clavier va s'ouvrir sur mobile et tablette, ce qui ultra intrusif et non utilisable
Il ne faut donc surtout pas mettre des focus partout...

par contre, on pourrait envisager que l'appui d'une touche comme "F2" puisse placer le curseur dans le champ recherche... mais bon, quel intéret ?
