### ISSUE TITLE
Ecran "série", numérotation des items

### ISSUE THREAD

**Issue by vergeylen** [svergeylen/collector#22]
Voir dans la série "Alter Ego", j'ai adapté la numérotation des albums en me référençant à la "saison" et colletor a accepté 1-xx  et 1-yy. C'est c'est bon pour toi, c'est intéressant (par exemple il y a aussi deux saisons pour Uchronies)

**Comment by svergeylen** [comment]
Bug. 
Il faut repenser le tri des items en fonction de leur numéro (composé). Le oucis vient quand les numéros ne sont pas des chiffres (un comble !)

**Comment by vergeylen** [comment]
Pas de souci pour abandonner l'idée . On peut commencer à numéroter la 1ère saison par 101 etc, la deuxième saison par 201 etc...

**Comment by svergeylen** [comment]
Voilà, c'est fait. Le nouveau site supporte les notations comme 1.1 puis 1.2 puis 1.3 de façon à pouvoir noter d'éventuels cycles ou groupement de BD :-) 
Par contre, on ne peut plus mettre de lettre dans les... numeros (ca parait logique, mais ca simpliefie drastiquement le tri par ordre de numéro !)
:-)
