### ISSUE TITLE
Lieu(x) de rangement

### ISSUE THREAD

**Issue by vergeylen** [svergeylen/collector#26]
Sans doute plus particulièrement nécessaire pour la catégorie "Livres techniques", pouvoir préciser où est rangé le titre concerné (en général, il s'agit d'un entreposage à long terme, autant savoir où)

**Comment by svergeylen** [comment]
@dvergeylen Est-ce que les nouveaux "tags" permettraient de gérer cela en plus ? D'après moi, oui, mais il faudra inventer une vue qui permet de distinguer les tags de lieux de autre (ca, je vois pas du tout !!)

**Comment by dvergeylen** [comment]
Oui oui oui 😊
