### ISSUE TITLE
Génération d'une vignette lorsqu'un URL est collé comme nouveau message

### ISSUE THREAD

**Issue by svergeylen** [svergeylen/collector#3]
Pour chaque lien posté, il faudarit générer un apercu plus joli que l'URL en lui même, un peu comme facebook le fait.

Apparement, impossible en pur javascript (pas moyen de loder des page depuis le JS ?)

**Comment by svergeylen** [comment]
https://stackoverflow.com/questions/11854866/using-jquery-and-rails-to-generate-preview-of-link

**Comment by svergeylen** [comment]
https://github.com/socialcast/link_preview

**Comment by svergeylen** [comment]
https://github.com/gottfrois/link_thumbnailer

**Comment by dvergeylen** [comment]
Tu peux éditer un post, ça évite ceux "subscribed" à l'issue (= moi) de recevoir un email de notif par lien posté. :wink: 

Tu peux franchement écrire la procédure toi-même, ce n'est pas difficile. Un fetch de l'URL, puis tu filtres sur les tags (dans le head) meta et tu cherches les attributs "og" (open graph):

```html
<meta property="og:title" content="Gamification Schemes made easy" />
<meta property="og:type" content="website" />
<meta property="og:description" content="Combine simple to complex mechanics to create gamified loyalty programs at large scale" />
<meta property="og:site_name" content="Place2Be.io" />
<meta property="og:image" content="https://place2be.io/assets/p2b_512px-b311d304bf91543d5db167afc9994c023d68536c8d381546038b51895d99ebf5.png" />
```

Tu peux alors nourrir un component react avec ces infos j'imagine, ou faire un rendu de partial sans layout... :thinking: 

Standard [OpenGraph](http://ogp.me/) (TOUS les crawlers l'utilise: FB, Twitter, linkedIn, ...)

**Comment by svergeylen** [comment]
Fait :-) :-)
(éventuellement pener à faire une vignette différente pour youtube, afin d'avoir un player directement intégré dans le fil d'actu"
