### ISSUE TITLE
Ordre de présentation des titres

### ISSUE THREAD

**Issue by vergeylen** [svergeylen/collector#31]
Dans les séries existantes, la nouvelle entrée s'affiche avant la première entrée de la série : 
Jeremiah 35 devant 1
XIII 11 devant 3
Thorgal Jeunesse 5 devant 1
Winch 21 devant 1
Châteaux Bordeaux 8 devant 1
Sangre 2 devant 1

**Comment by svergeylen** [comment]
oui, je comprends pas... pourtant toutes le autres séries qui ont des numéros similaires fonctionnent bien et sont bien triées... je vois pas trop.... c'est un problèume foireux entre int / float / string
