### ISSUE TITLE
Dans une série affichée, repasser sur un champ "recherche"

### ISSUE THREAD

**Issue by vergeylen** [svergeylen/collector#32]
- Quelle que soit la série affichée, le champ "Recherche" en haut à droite fait apparaître un écran  [Recherche de "" ] qui propose "50 séries trouvées" (et propose d'ailleurs toujours la même liste de 50 séries

**Comment by svergeylen** [comment]
Ha oui, effectivement.... c'est du à la modif que tu as demandée pour les séries (champ recherche perso) qui a cassé la représentation du modele "search"... il faut refaire le champ supérieur.... :-(
