### ISSUE TITLE
Bouton "Haut de page"

### ISSUE THREAD

**Issue by vergeylen** [svergeylen/collector#40]
Certains écrans deviennent long à défiler. Ce ne serait pas mal si sur tous les écrans figurerait en permanence en bas à droite un bouton qui renverrait au top de la page affichée (ex. eBay)

**Comment by svergeylen** [comment]
OK, facile...

    var body = $("html, body");
      body.stop().animate({scrollTop:0}, 500, 'swing', function() { 
         alert("Finished animating");
     });`
