### ISSUE TITLE
les heures ne s'affichent pas avec un 0 devant les chiffres seuls

### ISSUE THREAD

**Issue by svergeylen** [svergeylen/collector#43]

**Comment by dvergeylen** [comment]
Lol 😄

http://ruby-doc.org/core-2.4.2/String.html#method-i-25

```ruby
"%05d" % 123  #=> "00123"
```

**Comment by svergeylen** [comment]
Non, c'est du js ;-)

**Comment by dvergeylen** [comment]
Aok facile alors:

```javascript
var d = new Date();
console.log( ('0' + d.getMinutes()).slice(-2) );
```
`.slice(-2)` ne prendra que les deux derniers digits en partant de la droite :wink: 

Essaie de donner + de liens vers le code quand tu crées des issues, ça permet de montrer des exemples sur des cas réels directement. :smiley:  Quand tu résouds des issues aussi, ça permet de directement aller au commit pour voir comment cela a été résolu. Tu le fais déjà partiellement mais par exemple #27, #38 ne le sont pas, ce qui rend difficile la différenciation avec des issues closed par choix de design comme #48 où il n'y a pas de commit à faire.

Typiquement #12 je n'ai pas été voir non, parce qu'il n'y a pas de lien vers le commit qui me montre comment tu as fait ça et comme tu commits comme un fou, c'est compliqué de le retrouver si je ne vais pas voir dans les 12h où tu as commité.. :laughing:

**Comment by svergeylen** [comment]
tu veux faire des revues de tout le code que j'écris ? ok, j'essayerai ;-) Par contre, je vois pas comment linker des issues au code... c'est juste des pene bete quand je "vois" quelque chose à corriger... ;-) p : tu vas sur le site au fait ? parce qu'à part Luc...
