### ISSUE TITLE
Sécuristation HTTPS : afficher du contenu mixte (og:image) détruit le cadenas vert

### ISSUE THREAD

**Issue by svergeylen** [svergeylen/collector#48]
Le warning "contenu mixte" au lieu "page sécurisée" s'affiche parce que la page La Une inclut des images provent de sites web tiers... comme les thumbnails des liens copiés/collés....

Est-ce grave ? Faut il importer l'image sur le serveur collector ? (à la base je préférais que non comme ca c'est vachement plus simple....)

**Comment by dvergeylen** [comment]
Non, je ne téléchargerais pas l'image si elle ne provenait pas d'un https (pas un drame)

**Comment by svergeylen** [comment]
On, donc je laisse comme actuellement et on garde le parking pour les images qui viennent de liens http ...:-)
