### ISSUE TITLE
Permalink pour un post (accessible depuis l'extérieur après login)

### ISSUE THREAD

**Issue by svergeylen** [svergeylen/collector#49]
sera aussi utile pour le feed rss qui, pour le moment, ne permet pas d'afficher un seul post ...

**Comment by svergeylen** [comment]
@dvergeylen  Parfois le message de commit ne marche pas pour fermer l'issue... je comprends pas trop (problème de branche ?) Ici par exemple, cela devrait etre closed....

**Comment by dvergeylen** [comment]
Sûrement, parce que tu commits dans master mais la branche principale est configurée comme 'dev'. Donc si tu merges master sur dev alors toutes ces issues devraient s'afficher closed.

Le mieux est d'aller dans les réglages et indiquer que la branche principale est master et non dev (et, au pire, supprimer dev).

:thinking:

**Comment by dvergeylen** [comment]
Settings > Branches > "Default Branch" (je ne sais pas le faire moi, c'est le owner qui peut faire ça)

**Comment by svergeylen** [comment]
On fait :-) on verra à l'avenir :-)
