### ISSUE TITLE
Ordre d'affichage des items dans series#show

### ISSUE THREAD

**Issue by vergeylen** [svergeylen/collector#55]
Les 8 BD ajoutées vendredi 17/11 ne semblent pas avoir été reprises dans le news (Aquablue et Alter ego)
Dans la série Alter ego, les nouveautés s'ajoutent en tête de liste (lié à la gestion des 1.xx)

**Comment by svergeylen** [comment]
C'est corrigé pour la partie 1 et ce era pour plus tard pour l'ordre des éléments...
QUelle horeur que cet ordre qui n'est jamais le bon depuis le début... grrr... (à faire)

**Comment by svergeylen** [comment]
Dans  collector/app/models/series.rb  rempalcer

    self.items.includes(:users).sort_by{ |a| [a.number.to_i, a.name] }

par

    self.items.includes(:users).sort_by{ |a| [a.number.to_f, a.name] }
