### ISSUE TITLE
Difficulté pour savoir quelles pièces je joins lorsqu'il y a plusieurs liens internet

### ISSUE THREAD

**Issue by vergeylen** [svergeylen/collector#56]

**Comment by svergeylen** [comment]
Chaque message est fait pour poster une vignette, càd 1 lien.... c'est pareil sur facebook... est-ce un soucis ? 
Idée 1 : coller l'éventuel second lien comme commentaire
Idée 2 :  créer un autre message pour un second lien (qui n'a probablement rien à voir ;-) )
Idée 3 : mettre un seul lien et on verra bien de nous même s'il faut cliquer pour lire plus loin ???? ;-)

**Comment by vergeylen** [comment]
Coucou Stéphane,
Pas de souci
Je ne savais pas qu'un unique lien "ouvrait la voie"
Si deux liens = le 2ème en commentaire + info de ma part dans le texte. 
Aucun problème
Bizz
L.

ps: les bonzaïs ont survécu à ton absence j'espère ;-)

**Comment by svergeylen** [comment]
OKi super :-) Comme xpliqué sur La Une, il faut coller le lien dans le texte directement et ne pas utilier l'icone trombone... Cela crée la vignette directement (et enlève le lien http:///...... du texte quand cela réussi) :-)
