### ISSUE TITLE
Suggestion : fleche "retour haut de page" (2)

### ISSUE THREAD

**Issue by vergeylen** [svergeylen/collector#60]
Si possible afficher fléche "haut de page" sur toutes les pages : voir Bernard Prince pour voir "17" faut descendre mais pour choisir une nouvelle série faut remonter pour cliquer sur "chercher". Ca fait bcp de scroll

**Comment by svergeylen** [comment]
OK. Navbar fixe en haut devrait simplifier tout cela. Je vais y réfléchir
