### ISSUE TITLE
bug image de profil pour nouveau commentaire ?

### ISSUE THREAD

**Issue by svergeylen** [svergeylen/collector#62]
![image](https://user-images.githubusercontent.com/2971168/33657776-988d36c4-da7a-11e7-8471-956b827485b5.png)

**Comment by svergeylen** [comment]
"Identifiant utilisateur erroné"

**Comment by svergeylen** [comment]
Le problème vient du caching.... une foi que le cache a fait le "new comment" avec l'utiliateur 1, il le reprend tel quel pour tout le monde... Il faudrait virer le caching pour ce fragment là.... ou bien l'extraire du caching global du post...
@dvergeylen comment faire ca ?? cela me semble bien complexe...

**Comment by dvergeylen** [comment]
A mon avis il faut utiliser le Fragment caching:

http://guides.rubyonrails.org/caching_with_rails.html#fragment-caching

Ca génère une clef unique par fragment, lorsqu'un fragment est demandé à nouveau, celui-ci présente une nouvelle clef unique, donc non cachée, donc il regénère un rendu (d'après ce que j'en ai compris). :wink:

**Comment by svergeylen** [comment]
fait hier :-)
