### ISSUE TITLE
Suggestion : La Une et.... la Deux

### ISSUE THREAD

**Issue by vergeylen** [svergeylen/collector#74]
Pour le moment, toutes les nouvelles filent sur "La Une" et c'est très bien mais c'est aussi un peu un "melting pot" des genres. Et si en plus de "La Une", on créait "La Deux" qui serait préférentiellement réservée aux échanges techniques et aux infos du net pûrement techniques qui n'intéressent que nos deux administrateurs et laisser La Une pour toutes les infos plus généralistes ou génériques. Barre de tâches à l'ouverture "La Une + Collector" deviendrait "La Une + La Deux + Collector". Perso, je suivrais les deux types de news mais je pense que nos compagnes se contenteraient bien de suivre davantage La Une plus générique (les photos, les articles de presse, les infos entre-nous etc.....)

**Comment by svergeylen** [comment]
Haha, excellente idée... à réfléchir ;-) ;-)

**Comment by vergeylen** [comment]
Je trouve que c'est une bonne idée.
Quand je vois le défilement énorme à faire pour retrouver un post qui 
date d'un ou deux jour (regarde par ex les murs peints dans la chambre)
On n'a plus vraiment envie de descendre, de descendre....
Toutes les news sont avec vignettes et l'affichage des vignettes prend 
beaucoup d'espace sur chaque écran.
Ou peut-être ajouter un bouton "passer en mode lien ou en mode vignette" ?

**Comment by svergeylen** [comment]
Je ferme ce poitn pour le moment car pas prioritaire. La recherche en haut à droite permettra de retrouver tout et n'importe quoi, y compris par date (c'était les liens "archives" de la colonne de droite au début, si tu te souviens)
