### ISSUE TITLE
Remplace React component Ago par du simple javascript

### ISSUE THREAD

**Issue by svergeylen** [svergeylen/collector#77]
le retrait de React empeche La Une de s'affiche complètement. Il faut réimplementé l'afficheg d'une date (fixe) "il y a 3 minutes" (fixe, pas besoin que cela soit mis à jour toutes minutes, cela ne sert à rien en fait) à partir d'une date rails et virer l'appel a react.

**Comment by svergeylen** [comment]
fait.

**Comment by dvergeylen** [comment]
Peux-tu lier le Issue que tu résouds quand tu commits? Sinon c'est comme si on était dans un fichier Excel, pas moyen de voir la modification de code liée à un problème.

Autre suggestion, ajoute un label genre "Not Now" et tu tagge les issues que tu ne feras pas maintenant (ou alors un milestone "far future" et tu ajoutes les issues concernées dedans).

Ca permettrait de ne pas avoir à les fermer et donc de voir la différence entre les issues fermées parce qu'elles sont résolues de celles fermées parce qu'elles sont pos-posées. "Won't Fix" peut aussi indiquer qu'elles ne seront jamais implémentées (et là elles peuvent aussi être fermées)

**Comment by svergeylen** [comment]
commit 1e8a7abb6512e0d0092eb197f1c0c8a130beab90
