### ISSUE TITLE
Requete pour afficher "derniers ajourts" par.. catégorie

### ISSUE THREAD

**Issue by svergeylen** [svergeylen/collector#78]
Auparavant, une requete simple permettait d'afficher les derniers items ajoutés (ou modifiés, càd pour lesque un attachement avait été ajouté) par catégorie...
Le retrait des catégorie et la profondeur infinie de l'arbre des folders (=ex-tags) ne permet plus de faire cela facilement.
il faudrait faire un requete générique dans model > Folder pour afficher les derniers items de ce folder (et potentiellement sou folders, donc !) 
Attention aux performances, ca cette requete sera lancée très souvent (folder > show)

**Comment by dvergeylen** [comment]
Normalement (je n'ai pas encore de quoi tester), tout Item doit avoir l'ensemble des folders dont il fait partie dans l'association ownertag.

Ceci permet de classer les Items ayant "BD" comme folder, même s'ils sont bien plus profond dans la hiérarchie. 👍

**Comment by svergeylen** [comment]
Ha oui, ce serait parfait, en effet... (à condition que toutes les bd possède bien le folder "bd"... ce qui va d'office etre oublié par Luc à la création de bd... mais c'est une autre question j'avoue)

**Comment by dvergeylen** [comment]
Ce serait très plaisant et générique en effet!

Je ne retrouve plus l'endroit où j'avais écrit que chaque Item devait avoir l'ensemble des folders dont il fait partie, ça aurait été utile de relire la spec que j'avais écrite... 🤔

Pour cette vue d'ajout de Folder à un nouvel, à mon avis il faut:

* Soit proposer des folders par défaut (et comme 95% du temps ce sont des BDs, mettre le tag BD par défaut)
* Soit présenter un éclaté des Folders et cocher ceux qu'on souhaite assigner (au plus profond de la hiérarchie). Le système se charge tout seul d'assigner tous les parents des folders à l'Item.

**Comment by svergeylen** [comment]
C'est fait :-)

(pour les root tags pour le moment, on verra s'il faut généraliser à tous les tags, mais cela n'a pas forcément de sens de présenter des news pour des sous-sous-sous-tags....)
