### ISSUE TITLE
Formulaire spécifique "Ajout BD"

### ISSUE THREAD

**Issue by svergeylen** [svergeylen/collector#79]
En créant un item, il faut lui associer un/des folders (ex-tags).... L'ajout avec javascript>chosen fonctionne mais il faut tester et affiner l'UX.
Il faut se focaliser sur la création d'une BD : 
 - faut il une vue dédiée à la création de bd (on avait dit oui et finalement je l'ai pas encore créé ?)
 - faut il une vue généraique pour ajouter "un item" quand une vue spécifique n'est pas dispo ?
 - faut il une vue générique qui est assez clarire pour tous les types (moi, je préférérais, à voir)

Le problème est qu'on va mettre le folder "Thorgal", mais on va oublier de mettre le folder "BD" ... et dès lors la database sera étonnement construite... 

Pour le moment, toutes les BD ont le folder "nom de la série" et "bd"... comme tu voulais... afin de pouvoir faire une recherche par folder (plus tard)...

**Comment by svergeylen** [comment]
Créer un formulaire d'ajout de BD spécialié qui reprend tous les tags du dernier items de la série BD affichée... ex : on veut ajouter Thorgal n°3, on recoit comme tag par défaut les tags du n°2, càd "bd", "thorgal", "vanhamme", "rosinski"

**Comment by svergeylen** [comment]
Voici le nouveau formulaire d'ajout de BD...
Il faut maintenant : 
 
- associer des tags existants ou en créer de nouveau (!)
- sauver les nouveau tags en les associant à des tags de chaque champs à des tags prédéfinis dans le code (first_or_create)
 


![screenshot_2018-09-13 vergeylen eu](https://user-images.githubusercontent.com/2971168/45495507-aad4e080-b773-11e8-8e45-7831c2b9fec4.png)

**Comment by svergeylen** [comment]
Pour remplacer le chosen_select vachement  vieillissant...
https://selectize.github.io/selectize.js/

**Comment by svergeylen** [comment]
Coucou, voilà j'ai à nouveau des unpermitted parameters dans le nouveau formulaire "ajout BD" : 

Submit de item ( item > create ), avec trois champs de tags de type "string" :series, :auteurs et :rangement...

Unpermitted parameters: :series, :auteurs, :rangement, :view

C'est logique, vu que ces champs n'existent pas dans le modèle Item... mais bon, j'ai fait 

`   params.require(:item).permit(:number, :name, :description, :attachments, series: [], auteurs: [], rangement: [], tag_ids: [])`

ou aussi

`      params.require(:item).permit(:number, :name, :description, :attachments, :series, :auteurs, :rangement, tag_ids: [])`

afin qu'il me laisse lire ces données, mais sans succès.

Forcément, ca marche en console... mais pas dans les controlleurs... (lol !) Par exemple, pour la série : 
`
@item.update_tags_with_parent("Thorgal", Tag.where(name:"Séries").first )`

Si tu as une bonne idée... ;-) 
https://edgeapi.rubyonrails.org/classes/ActionController/StrongParameters.html

**Comment by dvergeylen** [comment]
Stp.. Pour la 3ème fois, tu dois mettre des accolades 😑

```ruby
params.require(:item).permit(:number, :name, :description, :attachments, {series: []}, {auteurs: []}, {rangement: []}, tag_ids: [])
```

Le dernier argument n'a pas besoin d'accolades, même si c'est un array.

Tu auras probablement une erreur du genre `ActiveModel::UnknownAttributeError (unknown attribute 'series' for Item.)` mais ça c'est un autre problème.

**Comment by dvergeylen** [comment]
Parce que je t'ai déjà averti de cette particulartié de syntaxe [ici](https://github.com/svergeylen/collector/issues/91#issuecomment-420205917) et [là](https://github.com/svergeylen/collector/issues/91#issuecomment-420657436), mais tu ne tiens pas compte de l'entièreté de ma réponse, [tu essaies le 1er truc qui marche](https://github.com/svergeylen/collector/issues/91#issuecomment-420998993) sans comprendre... Alors forcément quand tu re-rencontres le problème tu ne sais toujours pas quoi faire...

Si tu codes des trucs non triviaux, tu dois passer beaucoup *beaucoup* plus de temps à lire de la doc qu'à coder. Tu dois augmenter ta compréhension globale du framework et ce temps est incompressible...

Pourquoi faut-il mettre ces fichues accolades? Parce qu'on est en Ruby, donc `permit` est une fonction qui s'exécute sur son objet (`params` de type `ActionController::Parameters`) et accepte des filtres et/ou un hash si une `key` peut avoir plusieurs instances. C'est documenté dans [`permit`](https://edgeapi.rubyonrails.org/classes/ActionController/Parameters.html#method-i-permit), ce n'est pas de la magie.

Pourquoi ça marche en console et pas dans l'application? Parce que `item_params` est une fonction `private` dans un `ApplicationController` (Rails 4+), qui n'est pas du tout impliquée dans le flow des données lorsqu'elles sont manipulées en console (qui manipule directement des `ActiveModel`). Alors forcément si tu ne fais pas appel à `permit`, tu n'auras pas de `unpermitted parameters`...  C'est [la première phrase](https://guides.rubyonrails.org/action_controller_overview.html#strong-parameters) de la section Strong Parameters du Rails Guide sur Action Controller, ce n'est pas de la magie...

Pourquoi est-ce qu'il y a maintenant `UnknownAttributeError` ? Parce que Rails utilise l'excellent `ActiveRecord` qui est un ORM donc chaque instance d'objet représente une entrée correspondante dans la table du même nom et tous ses champs sont mappés automatiquement. Si tu ajoutes des champs à l'objet, il seront inconnus car ils n'existent pas dans la database et ne peuvent pas être inférés.   C'est décrit dans [le deuxième paragraphe de la doc](https://guides.rubyonrails.org/active_record_basics.html#object-relational-mapping) sur ActiveRecord, ce n'est pas de la magie.
Si tu veux ajouter des champs, tu dois définir des `virtual_attributes` ([railscast](http://railscasts.com/episodes/16-virtual-attributes-revised)).

Je trouve que le développement du Collector 2.0 est vraiment une très bonne chose, aucun doute là-dessus et justement, puisque le projet n'est pas facile (on parle quand même de coder des associations many-to-many polymorphiques) ça demande un mindset beaucoup plus "développeur" que "assembleur". Effectivement, ça passe par des excellents commit messages (comme tu le fais déjà), par une bonne gestion des issues avec des liens et des références, par une longue lecture de la doc, par une compréhension profonde des interactions entre tous les `Active*` (pas évidentes) et par les paradigmes encouragés en Ruby.

Tout ça ne s'acquiert pas en quelques temps, ça prend des années et moi-même je me considère pas du tout comme un expert à ce petit jeu. C'est un apprentissage quotidien qui ne s'arrête jamais. Alors je sais chaque fois je passe pour l'enquiquineur mais quand je te donne une proposition de solution, essaie de ne pas juste l'appliquer mais de voir un peu plus large, il y a peut-être du bon à prendre... Je serai ravi de t'aider (ravi, vraiment, d'ailleurs j'essaie systématiquement de te faire des [réponses complètes et reproductibles](https://github.com/svergeylen/collector/issues/90#issuecomment-421266440)) mais ça ne marchera que si tu es plutôt "cool, j'ai de nouveaux indices en plus" que "marche pô, solution non copier-collable"...

Bisous

**Comment by svergeylen** [comment]
Bein, oui, je sais tout ca... ca fait des années que tout cela existe, merci... pas besoin de faire la morale en plus... ?
Le truc, c'est que je pense pas qu'il faille créer ces attributs complémentaires, vu qu'on ne souhaite pas les sauver... ! donc rien de tout ceci ne me semble utilisable, bien que c'est certainement correct...

La différence entre toi et moi c'est que toi, c'est ton métier depuis plusieurs années, et moi, je n'ai quelques instants par ci par là pour implémenter ton idée de tags afin que tu adhères au collector... et je peux te dire que c'est pas simple de trouver de la motivation, même avec tes réponses complètes...  Je vais tenter une autre approche...

**Comment by dvergeylen** [comment]
> Je vais tenter une autre approche...

C'est bien dommage...

>[...] c'est ton métier depuis plusieurs années

C'est *devenu* mon métier parce que j'ai appliqué cette approche...

**Comment by svergeylen** [comment]
L'autre approche, c'était de tenter un form_tag au lieu d'un form_with(model).... cela marche, mais c'est moins beau... je pense qu'il faut que le code soit beau, mais j'imaginais au départ que tu m'aides dans le code plutôt que de m'expliquer Rails... Je pense qu'on ne s'est pas compris...

**Comment by svergeylen** [comment]
Allez, ca repart dans la bonne direction aujourd'hui.... "Chouette j'ai des indices en plus écrits au -dessus"... la journée commence par un railscast sur - surprise - les virtual attributes :-/

**Comment by dvergeylen** [comment]
Super! Je te réponds sur #90 parce que j'ai trouvé une façon super de faire (grâce aux éclairages que tu donnes)

**Comment by svergeylen** [comment]
voir e02b2395b4d44f789ca398dafef515ad9502fef7
