### ISSUE TITLE
Les heures ont décalées de deux heures en retard

### ISSUE THREAD

**Issue by svergeylen** [svergeylen/collector#8]
Comment faire pour que Rails sache dans quel fuseau horaire on est ?

**Comment by dvergeylen** [comment]
Ca dépend.

* Si c'est pour que Rails soit en time zone locale, c'est:
  ```ruby
  # application.rb
  config.time_zone = Brussels' 
  ```
  liste complète via `rake time:zones:local` et `rake time:zones:all`.

* Si c'est pour que Rails sauve en DB autre chose qu'une heure en UTC:
  ```ruby
  # application.rb
   config.active_record.default_timezone = :local
  ```
* Si rien de tout ça ne marche, tu peux toi-même modifier l'heure d'encodage en DB:
  ```ruby
  # Warrior
  DateTime.now.new_offset(0).advance(seconds: DateTime.now.utc_offset)})
  ```

**Comment by svergeylen** [comment]
Haha, t'es chaud toi !  :-) Comment savais tu que j'avais créé ce bug ? ;-) J'avais fait exprès de bien checké que tu n'étais pas inscrit pour ne pas recevoir plein de notifications ;-) 
Du coup, ce matin, je checkais l'information pendant ma mini pause pour les time_zone, je la trouve, et je vois que tu m'as déjà tout mis ! :-) Haha, trop au taquet, le frangin (attention, à ne pas dessaler quand on navigue au taquet ;-) lol) 
Bon, et sinon, c'est bien ma première réponse qui doit être la bonne, non ? Je ferai la modif ce soir ;-) <3

**Comment by dvergeylen** [comment]
Facile, quand quelqu'un t'ajoute à un projet, tu es automatiquement assigné à "watch", ce qui signifie que toute activité te sera notifiée, comme car tu es subscribed automatiquement à n'importe quel issue + pull request (qui est vu comme une forme d'issue par github).

Je peux me désinscrire de watch, ce qui rendrait ce repo silencieux, sauf ce pour quoi je me serais manuellement subscribed.
