### ISSUE TITLE
Gestion espace de stockage (archivage)

### ISSUE THREAD

**Issue by svergeylen** [svergeylen/collector#88]
Suppression / archivage du passé à méditer
+ getsion de l'espace disque à vérifier / monitorer (c'est pas que 10Go un VM ovh ?? c'est peu !)

**Comment by svergeylen** [comment]
Excellente idée :-) (ne pas oublier les performances quand on charge ~30 images de la Une, il faut que cela charge (les thumbnails du moins) en moins de ... 5 secondes ? A tenter, en tout cas)

**Comment by dvergeylen** [comment]
Il semblerait qu'il soit possible d'implémenter un nouveau Service pour ActiveStorage en implémentant [cette classe abstraite](https://github.com/rails/rails/blob/ed56a031041a868eeeb439d8b79d04565be1286f/activestorage/lib/active_storage/service.rb)!

Une implémentation naïve pourrait peut-être se faire rapidement (sans implémenter toutes les fonctions, ou en tout cas pas de façon efficiente).

**Comment by svergeylen** [comment]
je propose de d'abord faire des tests de performances en modifiant les href d'une vingtaine d'images sur une page de vergeylen.eu et de voir comment le téléchargement des photos se fait sur le cloud (rapidement ou non), (en sachant que dans ce cas là, on bypass déjà la classe abstraite en question vu qu'on hardcode les liens, c'est donc un cas plus favorable que le cas réel, mais il faudrait voir si la fluidité est au rendez-vous... )
Je pense à ca parce l'affichage des vignettes dans l'appli owncloud, c'est environ 1 minute pour 20 vignettes, même quand elles sont générées à l'avance... ) donc a priori ce serait faisable mais pas assez rapide à l'usage... (?)
