### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by dvergeylen** [svergeylen/collector#9]
http://railscasts.com/episodes/87-generating-rss-feeds-revised

https://www.codingfish.com/blog/129-how-to-create-rss-feed-rails-4-3-steps

Ca permettrait de l'ajouter aux lecteurs de flux RSS en évitant d'avoir à "venir voir' régulièrement.

**Comment by svergeylen** [comment]
Oui, super idée (!) mais tu n'aurais pas les photos (à venir) ni les liens (quoique ca, c'est p-e supporté par le lecteur de flux rss).
Ps : a prévoir aussi pour les commentaires sur les posts ? ou juste les posts ??
pps : j'ai fait un truc assez simple qui change le CSS en fonction de l'heure du dernier login... càd que les posts déjà vus sont grisé et les nouveaux posts sont blancs... tout simple et utile non ? (idem pour les commenatire, le bouton est bleu quand il y a des nouveaux commentaires)
