### ISSUE TITLE
Table items_tags

### ISSUE THREAD

**Issue by svergeylen** [svergeylen/collector#92]
A quoi peut bien servir la table items_tags dans la banque de données ?

Serait-il possible qu'elle soit devenue inutile suite aux modifs de relations que tu faites ? (et donc c'est la table owertags qui reprend tous les liens entre tags eux-mêmes mais entre items et tags également)

Du coup, a supprimer ? (mais avant ou après l'import final de données ?)

**Comment by dvergeylen** [comment]
Euh oui, la table `owerntags` n'est qu'un renaming de `item_tags`, en tout cas c'est [ce que j'avais fait](https://github.com/svergeylen/collector/pull/54/files#diff-9f1b6f5d23f803e4ede757c026c74879) dans ma pull request.

Il faudrait la supprimer du coup, mais j'ignore s'il y a des choses dedans (à mon avis oui, mais plus mis à jour vu que les associations ont été redirigées vers `ownertags`, un nouveau model qui n'existait pas dans l'implémentation originale. La table existait mais pas le model, il me semble que tu avais décrit la relation comme `habtm` (qui ne permet pas de préciser une association polymorphique)

**Comment by svergeylen** [comment]
ha bein non, j'ai fais mieux...  Si je supprime, je perds tous les auteurs des items (les anciens "tag" en fait)... du coup, je viens d'ajouter la ligne suivant dans item : 
````
# Temporaire pour la migration de l'ancien site.
# Ajout d'un lien vers l'ancienne table items_tags pour lire les auteurs des BD !
has_and_belongs_to_many :old_tags, source: :items_tags, class_name: 'Tag'
````

pour pouvoir accéder à ces infos et les migrer dans ownertags :-) ce qui est fait depuis ce midi ;-) et dès que cette migration aura été faite sur les données en production, on pourra virer par migration items_tags... car devenue redondante (et surtout plus utilisée).

Voir les ("trèès sympaas") scripts de migration tout beaux faits en tache rake :-) :-) 
`lib/tasks/db.rake`
