### ISSUE TITLE
Représentation graphique d'un tag

### ISSUE THREAD

**Issue by svergeylen** [svergeylen/collector#93]
Luc demande qu'un tag comme Noirmoutier puisse être affiché comme une icone, image ou photo. De cette facon, on pourrait voir certains tags comme des images claires et alléger l'aspect graphique avec des icones bien connues (principalement pour le type d'item - comme BD/bonsai - et les rangements - Noirmoutier, limal, escalier, etc)

Conception : on pourrait ajouter la possibilité d'ajouter un attachment optionnel à chaque tag et afficher ce tag comme un cercle contenant cette icon (taille : tiny) lorsque l'icone existe, le nom autrement. Dans les formulaires, c'est bien évidemment le noms qui resterait affiché (éventuellement ajouter l'image à coté si popper.js le permet aisément)

**Comment by dvergeylen** [comment]
Hum, ça me parait compliqué :thinking:

Proposition: ajouter un champ emoji (où la liste est longue, [vraiment longue](https://unicode.org/emoji/charts/full-emoji-list.html)) et un attribut virtuel `full_name` qui concatène les deux pour l'affichage: 

```
def full_name
"%s %s" % [self.emoji, self.name]
end
```
Modifications minimales et affichage simplifié dans la barre de tags

**Comment by svergeylen** [comment]
Non, je pense que c'est plus simple d'afficher le tag sous forme d'image quand un attachment est ajouté à l'image, ou le name quand il n'y a pas d'attachment... mais, je n'ai pas mis "help wanted" donc à priori je vais gérer ca de mon coté, tu ne dois pas t'ennuyer avec toutes les issues... par contre, pour les strong parameters, ca ne marche pas du tout, donc la je veux bien que tu fasses qqch ;-)
