### ISSUE TITLE
Déplacement des photos dans /uploaded_files

### ISSUE THREAD

**Issue by svergeylen** [svergeylen/collector#97]
Coucou,
Le déplacement des photos s'est bien déroulés, mais certaines photos ne passent pas (étrangement ce sont toutes celles que tu as postées, mais je ne sais pas pourquoi...)

Les photos sont bien là, car en affichant le post en plein page, les photos s'affichent... : https://www.vergeylen.eu/posts/587 
par contre, les miniatures ne s'affichent pas (toutes) dans La Une (photo du passé, j'entends)...

Autre exemple : 
https://www.vergeylen.eu/posts/598 --> pas dans la Une mais bien dans le post > show

Peut-etre régénérer les miniatures ? ou vérifier ou sont les images ?

**Comment by dvergeylen** [comment]
Je suis le seul à poster des photos je pense, les autres images sont générées sur base d'une URL d'image, pas vrmt d'un upload à mon avis.

Il s'agit bien d'un problème de cache, l'URL est encore l'ancien:
```html
<img class="img-thumbnail" src="/system/attachments/images/000/000/563/medium/IMG_20181001_193231626_HDR.jpg?1538416101" alt="Img 20181001 193231626 hdr">
```

Dans `app/views/posts/_post.html.erb` la section est bien sous une partie mise en cache:
```ruby
<% cache post do %>
   [...]
          <div class="col-xs-6">
            <%= link_to post_path(post, slide_id: i) do %>
              <%= image_tag "/" + a.image.url(:medium), class:"img-thumbnail" %>
            <% end %>
          </div>
   [...]
<% end %>
```

Essaie `Rails.cache.clear` en console de production `rails console production` :thinking: 

Je suis sur autre chose mais essaie déjà ça, avec le restart du serveur pour l'autre problème d'assets. Ça pourrait résoudre une partie. Bisous

**Comment by svergeylen** [comment]
Yesss ! Belle collaboration sur ce coup là (et ma migration a fonctioné nickel du coup !)

**Comment by svergeylen** [comment]
Je viens d'ajouter au script de depoly ;- )  bundle exec rake tmp:cache:clear

**Comment by dvergeylen** [comment]
Tu peux supprimer les anciennes du coup (dans `public/system/...`)

**Comment by svergeylen** [comment]
ok, mais ne cloture pas les taches quand il reste des choses à faire, stp.

**Comment by svergeylen** [comment]
Il faut encore vérifier si on peut supprimer le dossier public/system/users qui semble contenir les avatars des users (je ne l'ai pas supprimé encore car je ne pense pas avoir modifié cela)

**Comment by svergeylen** [comment]
Bug des anciennes photos : il manque les "0" en préfixe dans certains patch pour les attchment dont l'id < 100 ... lol

**Comment by svergeylen** [comment]
done :-) 

```
#!/bin/bash
for i in 1 2 3 4 5
do
   echo "Welcome $i times"
done
```
