### ISSUE TITLE
En production, les librairies ne sont pas chargées correctement

### ISSUE THREAD

**Issue by svergeylen** [svergeylen/collector#98]
![image](https://user-images.githubusercontent.com/2971168/46807560-7c462780-cd6a-11e8-9e9c-7b8ede5cdf78.png)

C'est loin detre le résultat escompté ! Il y a surement des trucs qui ne sont pas chargés en production, mais de là à savoir lesquels....

**Comment by svergeylen** [comment]
apparemment, selectize.js est bien chargé mais rien ne se passse...

pourtant, sur certaines pages, j'ai un truc immonde qui s'affiche ... ?? Il y aurait un processus en background qui mouline les assets ? (super lent, alors, parce que cela fait 10 minutes... ;-) )

![capture d ecran de 2018-10-11 15-38-51](https://user-images.githubusercontent.com/2971168/46808102-caa7f600-cd6b-11e8-88d0-900758990669.png)

**Comment by dvergeylen** [comment]
`bundle exec rake assets:precompile RAILS_ENV=production` s'est-il passé correctement? et `touch tmp/restart.txt` ? :confused: On dirait un problème de cache serveur... :thinking:

**Comment by svergeylen** [comment]
oui oui, c'est dans le script de déploiement automatique (./update_collector ) 
et pour le rake precompile, je suppose que non, ca a du foiré, mais je n'ai qu'un ouptup très sybillen ! 

```
yarn install v1.2.0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
info Lockfile not saved, no dependencies.
Done in 0.09s.
I, [2018-10-11T16:00:52.381862 #28380]  INFO -- : Writing /home/vgl/collector/public/assets/application-b8055a1cd4bc46e9f67af14d2d24e55a8a5b5e57c766dd80efe689e1f47c7ca8.css
I, [2018-10-11T16:00:52.382494 #28380]  INFO -- : Writing /home/vgl/collector/public/assets/application-b8055a1cd4bc46e9f67af14d2d24e55a8a5b5e57c766dd80efe689e1f47c7ca8.css.gz 

```

**Comment by svergeylen** [comment]
Apparement, c'est tout qui foire, parce que le carousel de photo n'est pas chargé non plus ! (?)

Voir https://www.vergeylen.eu/items/2632

Il y a surement eu un "abort" quelques part... mais aucune erreur affichée :-(

**Comment by dvergeylen** [comment]
J'ai essayé plusieurs trucs à chaud sur le serveur mais ça n'a pas marché.

A mon avis, tu dois au moins mettre selectize (.min.js et .css) dans `config/initializers/assets.rb` et les retirer de application.js et application.css (en développement et production, ces fichiers sont interprétés différemment).

Je pense qu'il ne parvient pas à trouver selectize, ce qui empêche la précompilation de la suite, ce qui explique que le reste du JS ne se charge pas...

0,09 secondes c'est la résolution des dépendances par yarn, par la compilation des assets qui est après (et différentielle). 😉

**Comment by svergeylen** [comment]
Ha bien, je préfère cela... une fois le cache de firefox supprimé, la libraisire selectize n'est tout simplement pas ajoutée du tout... surement un truc de git encore... (/vendor est-il dans le git ? sur github oui, mais pourtant ya pas la librarie, bizarre, je regarderai demain 

(PS : c'est pas automatique le purge du cache firefox avec la gestion de version des .js et .css ? je pensais que si, depuis l'introduction des assets pipeline ? quand on navigue sur un site normal, personne ne clear son cache habituellement ;-) )

**Comment by svergeylen** [comment]
J'ai ajouté les fichier js et css complets relatif au dossier "vendor" et cela ajoute bien les fichiers en production...

```
cd public/assets/selectize.js-master/dist/js/standalone/
vgl@vps371955:~/collector/public/assets/selectize.js-master/dist/js/standalone$ ls
selectize.min-be667fcbe1b78fc7934594f3094ae239a27c2929d79c62b76bb453b5e11b15dc.js
selectize.min-be667fcbe1b78fc7934594f3094ae239a27c2929d79c62b76bb453b5e11b15dc.js.gz
```

Cela dit, le path n'est plus le même vu que vendor/assets/javascripts/ disparait... dès lors, la librairie n'est toujorus pas chargée (et qu'est ce que c'est mal expliqué !)

**Comment by svergeylen** [comment]
je ne pense pas car ils disent que l'asset pipeline fait tout pour nous et qu'il faut avoir un seul tag <script> idéalement (performances ? pas très clair) Je pense que ca marche pour le JS en fait (depuis l'ajout du fichier js manuellement dans les assets à compiler), mais pas pour le css...


En cherchant, je trouve que les fichiers css sont importés AVEC l'extension .css ce qui pourrait faire foirer sont truc de hash256 qu'il ajoute au nom de fichier... je vais tenter ca dans quelques instants ..

**Comment by svergeylen** [comment]
Oui ! Ca, cela semble avoir fonctionné :-) :-) (il fallait (1) ajouter manuellement les fichiers dans vendor/ dans le tableau %w de precompilation (c'est contre intuitif, vu qu'on inclut une ligne plus haut explicitement le dossier entier "vendor".... mais cela ne suffit pas, il faut lister un par un les fichiers que l'on veut inclure, c'est même étonnant et peu gérable dans de gros projets) et (2) enlever l'extension .css dans le @import de application.css.scss (alors qu'il n'y a pas d'erreur en developpement car il trouve le fichier source ;-) ) Waouw, ca prend plus de temps que de coder la fonctionnalité ;-) lol
